# Generated by Django 5.0.6 on 2024-06-30 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("political & legal", "Political"),
                            ("environment", "Environment"),
                            ("technical", "Technical"),
                            ("financial", "Financial"),
                            ("community", "Community"),
                            ("business", "Business"),
                        ],
                        default="guide",
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("excerpt", models.CharField(max_length=150)),
                ("month", models.CharField(max_length=3)),
                ("day", models.CharField(max_length=2)),
                ("content", models.TextField()),
                (
                    "date_created",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
