# Generated by Django 5.0.6 on 2024-06-30 19:59

import blog.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=225, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to=blog.models.upload_to_path,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("political & legal", "Political"),
                            ("environment", "Environment"),
                            ("technical", "Technical"),
                            ("financial", "Financial"),
                            ("community", "Community"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "DRAFT"), ("publish", "PUBLISH")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
