# Generated by Django 5.0.6 on 2024-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_delete_blogpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="subtitle",
            new_name="excerpt",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="status",
        ),
        migrations.AddField(
            model_name="blog",
            name="file_upload",
            field=models.FileField(default=None, upload_to="uploads/% Y/% m/% d/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="level",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("advance", "Advance"),
                ],
                default=None,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("guide", "Guide"),
                    ("political & legal", "Political"),
                    ("environment", "Environment"),
                    ("technical", "Technical"),
                    ("financial", "Financial"),
                    ("community", "Community"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
