# Generated by Django 5.0.6 on 2024-06-26 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_type", models.CharField(max_length=100)),
                ("offer_location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(max_length=255)),
                ("offer_description", models.TextField()),
                ("community_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(max_length=100)),
                (
                    "images",
                    models.ImageField(
                        default="defaults/%(class)s_default.jpg",
                        upload_to="%(class)s_uploads/",
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_offers",
                        to="offers.offers",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(max_length=255)),
                ("offer_description", models.TextField()),
                ("community_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(max_length=100)),
                (
                    "images",
                    models.ImageField(
                        default="defaults/%(class)s_default.jpg",
                        upload_to="%(class)s_uploads/",
                    ),
                ),
                ("budget_goal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "surface_area_goal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_investment_limit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_offers",
                        to="offers.offers",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurfaceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(max_length=255)),
                ("offer_description", models.TextField()),
                ("community_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(max_length=100)),
                (
                    "images",
                    models.ImageField(
                        default="defaults/%(class)s_default.jpg",
                        upload_to="%(class)s_uploads/",
                    ),
                ),
                ("surface_type", models.CharField(max_length=100)),
                ("surface_area", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_offers",
                        to="offers.offers",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
