# Generated by Django 5.0.6 on 2024-07-03 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offers_created_at_offers_modified_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentoffer",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="projectoffer",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="surfaceoffer",
            name="offer",
        ),
        migrations.AlterModelOptions(
            name="investmentoffer",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="projectoffer",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="surfaceoffer",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="investmentoffer",
            old_name="community_type",
            new_name="offer_type",
        ),
        migrations.RenameField(
            model_name="projectoffer",
            old_name="community_type",
            new_name="offer_type",
        ),
        migrations.RenameField(
            model_name="surfaceoffer",
            old_name="community_type",
            new_name="offer_type",
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="cover_image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="offer_photos/"
            ),
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="file_upload",
            field=models.FileField(default=None, upload_to="uploads/investment_offers"),
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="offer_excerpt",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="progress",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investmentoffer",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="cover_image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="offer_photos/"
            ),
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="file_upload",
            field=models.FileField(default=None, upload_to="uploads/project_offers"),
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="offer_excerpt",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="progress",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="cover_image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="offer_photos/"
            ),
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="file_upload",
            field=models.FileField(default=None, upload_to="uploads/surface_offers"),
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="offer_excerpt",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="progress",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="investmentoffer",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectoffer",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="surfaceoffer",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Offers",
        ),
    ]
