# Generated by Django 5.0.6 on 2024-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_remove_investmentoffer_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentoffer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("Surface Offer", "Surface Offer"),
                    ("Project Offer", "Project Offer"),
                    ("Investment Offer", "Investment Offer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectoffer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("Surface Offer", "Surface Offer"),
                    ("Project Offer", "Project Offer"),
                    ("Investment Offer", "Investment Offer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surfaceoffer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("Surface Offer", "Surface Offer"),
                    ("Project Offer", "Project Offer"),
                    ("Investment Offer", "Investment Offer"),
                ],
                max_length=20,
            ),
        ),
    ]
