# Generated by Django 5.0.6 on 2024-07-04 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_investmentoffer_offer_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentoffer",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AlterModelOptions(
            name="projectoffer",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AlterModelOptions(
            name="surfaceoffer",
            options={"ordering": ("-start_date",)},
        ),
        migrations.RenameField(
            model_name="projectoffer",
            old_name="max_investment_limit",
            new_name="investment_amount",
        ),
        migrations.RenameField(
            model_name="projectoffer",
            old_name="surface_area_goal",
            new_name="surface_area",
        ),
    ]
