# Generated by Django 5.0.6 on 2024-07-04 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_alter_investmentoffer_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectoffer",
            old_name="budget_goal",
            new_name="max_investment_limit",
        ),
    ]
