# Generated by Django 5.0.6 on 2024-07-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_rename_budget_goal_projectoffer_max_investment_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentoffer",
            name="motivation",
            field=models.TextField(default="motivation text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectoffer",
            name="motivation",
            field=models.TextField(default="motivation text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="investment_amount",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="max_investment_limit",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surfaceoffer",
            name="motivation",
            field=models.TextField(default="motivation text"),
            preserve_default=False,
        ),
    ]
