# Generated by Django 5.0.6 on 2024-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_investmentoffer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='surfaceoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
