# Generated by Django 5.0.6 on 2024-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_investmentoffer_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoffer',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='projectoffer',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='surfaceoffer',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='investmentoffer',
            name='files',
            field=models.FileField(default=None, null=True, upload_to='file_uploads/investment_offers/'),
        ),
        migrations.AddField(
            model_name='projectoffer',
            name='files',
            field=models.FileField(default=None, null=True, upload_to='file_uploads/project_offers/'),
        ),
        migrations.AddField(
            model_name='surfaceoffer',
            name='files',
            field=models.FileField(default=None, null=True, upload_to='file_uploads/surface_offers/'),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='cover_image',
            field=models.ImageField(blank=True, default='offers_cover_images/default.png', max_length=200, null=True, upload_to='offers_cover_images/'),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='images',
            field=models.ImageField(default=None, upload_to='image_uploads/investment_offers/'),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='status',
            field=models.CharField(choices=[('Pre verification', 'Preverification'), ('Active', 'Active'), ('Post verification', 'Postverification'), ('Completed', 'Completed')], default='Pre verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='cover_image',
            field=models.ImageField(blank=True, default='offers_cover_images/default.png', max_length=200, null=True, upload_to='offers_cover_images/'),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='images',
            field=models.ImageField(default=None, upload_to='image_uploads/project_offers/'),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='status',
            field=models.CharField(choices=[('Pre verification', 'Preverification'), ('Active', 'Active'), ('Post verification', 'Postverification'), ('Completed', 'Completed')], default='Pre verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='surfaceoffer',
            name='cover_image',
            field=models.ImageField(blank=True, default='offers_cover_images/default.png', max_length=200, null=True, upload_to='offers_cover_images/'),
        ),
        migrations.AlterField(
            model_name='surfaceoffer',
            name='images',
            field=models.ImageField(default=None, upload_to='image_uploads/surface_offers/'),
        ),
        migrations.AlterField(
            model_name='surfaceoffer',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='surfaceoffer',
            name='status',
            field=models.CharField(choices=[('Pre verification', 'Preverification'), ('Active', 'Active'), ('Post verification', 'Postverification'), ('Completed', 'Completed')], default='Pre verification', max_length=20),
        ),
    ]
