# Generated by Django 5.0.6 on 2024-07-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_remove_investmentoffer_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoffer',
            name='files',
        ),
        migrations.RemoveField(
            model_name='investmentoffer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='projectoffer',
            name='files',
        ),
        migrations.RemoveField(
            model_name='projectoffer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='surfaceoffer',
            name='files',
        ),
        migrations.RemoveField(
            model_name='surfaceoffer',
            name='images',
        ),
        migrations.CreateModel(
            name='OfferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offer_file_uploads/')),
                ('investment_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='offers.investmentoffer')),
                ('project_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='offers.projectoffer')),
                ('surface_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='offers.surfaceoffer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offer_image_uploads/')),
                ('investment_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.investmentoffer')),
                ('project_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.projectoffer')),
                ('surface_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.surfaceoffer')),
            ],
        ),
    ]
