import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavigationBar } from "../components/common/navigartion-bar";
import { HeroSection } from "../components/homepage/hero-section";
import { Features } from "../components/homepage/feature-section";
import { FooterSimple } from "../components/common/footer-simple";
import { BlogCarousel } from "../components/blog/blog-carousel";
export function Home() {
    return (_jsxs(_Fragment, { children: [_jsx(NavigationBar, {}), _jsx(HeroSection, {}), _jsx(Features, {}), _jsx("section", { className: "py-24 relative", children: _jsx("div", { className: "w-full max-w-5xl px-4 md:px-5 lg:px-5 mx-auto", children: _jsxs("div", { className: "w-full justify-start items-center gap-8 grid lg:grid-cols-2 grid-cols-1", children: [_jsxs("div", { className: "w-full flex-col justify-start lg:items-start items-center gap-10 inline-flex", children: [_jsxs("div", { className: "w-full flex-col justify-start lg:items-start items-center gap-4 flex", children: [_jsx("h2", { className: "text-gray-900 text-4xl font-bold tracking-tight lg:text-start text-center", children: "Do you want to learn more about energy communities?" }), _jsx("p", { className: "text-gray-500 text-base font-normal tracking-tight lg:text-start text-center", children: "You can visit our resources to learn more." })] }), _jsx("button", { className: "sm:w-fit w-full px-3.5 py-2 bg-indigo-600 hover:bg-indigo-800 transition-all duration-700 ease-in-out rounded-lg shadow-[0px_1px_2px_0px_rgba(16,_24,_40,_0.05)] justify-center items-center flex", children: _jsx("a", { href: "/resources", children: _jsx("span", { className: "px-1.5 text-white text-sm font-medium leading-6", children: "Resources" }) }) })] }), _jsx("img", { className: "lg:mx-10 mx-auto rounded-lg", src: "src/assets/images/picture1.png", alt: "about Us image" })] }) }) }), _jsx("section", { className: "py-24 relative", children: _jsx("div", { className: "w-full max-w-5xl px-4 md:px-5 lg:px-5 mx-auto", children: _jsxs("div", { className: "w-full justify-start items-center gap-8 grid lg:grid-cols-2 grid-cols-1", children: [_jsx("img", { className: "lg:-mx-10 mx-auto rounded-lg", src: "src/assets/images/picture2.png", alt: "about Us image" }), _jsxs("div", { className: "w-full flex-col justify-start lg:items-start items-center gap-10 inline-flex", children: [_jsxs("div", { className: "w-full flex-col justify-start lg:items-start items-center gap-4 flex", children: [_jsx("h2", { className: "text-gray-900 text-4xl font-bold tracking-tight lg:text-start text-center", children: "Would you like to be part of your local energy community?" }), _jsx("p", { className: "text-gray-500 text-base font-normal tracking-tight lg:text-start text-center", children: "You can see all the active energy community projects and make proposals to be part of them." })] }), _jsx("button", { className: "sm:w-fit w-full px-3.5 py-2 bg-indigo-600 hover:bg-indigo-800 transition-all duration-700 ease-in-out rounded-lg shadow-[0px_1px_2px_0px_rgba(16,_24,_40,_0.05)] justify-center items-center flex", children: _jsx("a", { href: "/projects", children: _jsx("span", { className: "px-1.5 text-white text-sm font-medium leading-6", children: "Go to our Projects page" }) }) })] })] }) }) }), _jsx(BlogCarousel, {}), _jsx(FooterSimple, {})] }));
}
